version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5050:5000"
    environment:
      - PORT=5000
    volumes:
      - user-data:/app/data

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5051:5001"
    environment:
      - PORT=5001
      - USER_SERVICE_URL=http://user-service:5000
      - NOTIFICATION_SERVICE_URL=http://notification-service:5002
    depends_on:
      - user-service
      - notification-service
    volumes:
      - order-data:/app/data

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "5052:5002"
    environment:
      - PORT=5002

volumes:
  user-data:
  order-data: